name: Cross-Platform Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run compatibility tests
      run: |
        python test_platform_compatibility.py
    
    - name: Test import functionality
      run: |
        python -c "from iphone_camera_integration import create_dj_camera; print('✅ Imports successful')"
    
    - name: Test forced built-in camera
      env:
        FORCE_BUILTIN_CAMERA: "1"
      run: |
        python -c "
        from iphone_camera_integration import ContinuityCameraManager
        manager = ContinuityCameraManager()
        device = manager.detect_continuity_camera()
        assert device == 0, 'Built-in camera override failed'
        print('✅ Built-in camera override works')
        "
